create table "Student"(
"Id" int primary key generated by default as identity,
"FName" varchar(90) not null,
"LName" varchar(90) not null,
"MName" varchar(90) null,
"BDay" date,
"EntranceYear" int
);

create table "Subject"(
"Id" int primary key generated by default as identity,
"Title" varchar(100) not null
);

create table "Group"(
"Id" int primary key generated by default as identity,
"Title" varchar(100) not null
);

create table "StudentGrade"(
"StudentId" int references "Student"("Id"),
"SubjectId" int references "Subject"("Id"),
"Grade" int null,
"Year" int not null,
primary key("SubjectId", "StudentId", "Year")
);

create table "Course"(
"StudentId" int references "Student"("Id"),
"GroupId" int references "Group"("Id"),
"CourseYear" int not null,
primary key("StudentId", "GroupId", "CourseYear")
);